name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  FUK_VARIABLE: ${{ vars.FUK_VARIABLE }}
  ENV_CONTEXT_VAR: ${{ vars.ENV_CONTEXT_VAR }}
  ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
  ENVIRONMENT_STAGE: ${{ vars.ENVIRONMENT_STAGE }}
on:
  push:
    branches:
      - dev
      - develop/*
jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    steps:
      - name: Use variables
        run: |
          echo "repository variable : $REPOSITORY_VAR"
          echo "organization variable : $ORGANIZATION_VAR"
          echo "overridden variable : $OVERRIDE_VAR"
          echo "variable from shell $ENV_CONTEXT_VAR : $ENV_CONTEXT_VAR"
          echo "variable from shell $ENVIRONMENT_STAGE : $ENVIRONMENT_STAGE"
          echo "variable from shell $FUK_VARIABLE : $FUK_VARIABLE"
          echo "variable from shell vars : ${{ vars.toString }}"
        env:
          REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
          ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
          OVERRIDE_VAR: ${{ vars.OVERRIDE_VAR }}

      - name: ${{ vars.HELLO_WORLD_STEP }}
        if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ vars.GREET_NAME }}


